name: Sungi Kim
url: http://example.org
description: 

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Categories
   url: /category
 - title: Diary
   url: /diary
 - title: Archives
   url: /archives

collections:
  diary:
    output: true