name: Sungi Kim
url: sungikim.github.io
description: 

permalink: /posts/:year:month:day:hour:minute/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

defaults:
  -
    scope:
      path: "_*/photo"
    values:
      image: true
      sitemap: false
      layout: "post"

kramdown:
  hard_wrap: true
  
navigation:
 - title: About
   url: /about
 - title: Diary
   url: /diary
 - title: Memory
   url: /memory
 - title: Design
   url: /design
 - title: Book
   url: /book
 - title: Movie&Drama
   url: /movie
 - title: Make
   url: /make
 - title: etc.
   url: /etc

include:
  - _*/photo
  - _*/photo/*
  - _diary/photo
  - _memory/photo
  - _design/photo
  - _book/photo
  - _movie/photo
  - _make/photo
  - _etc/photo

collections_dir: ""

collections:
  diary:
    output: true
    permalink: /diary/:year:month:day:hour:minute/
  memory:
    output: true
    permalink: /memory/:year:month:day:hour:minute/
  design:
    output: true
    permalink: /design/:year:month:day:hour:minute/
  book:
    output: true
    permalink: /book/:year:month:day:hour:minute/
  movie:
    output: true
    permalink: /movie/:year:month:day:hour:minute/
  make:
    output: true
    permalink: /make/:year:month:day:hour:minute/
  etc:
    output: true
    permalink: /etc/:year:month:day:hour:minute/